import test from 'node:test';
import assert from 'node:assert/strict';
import { DatabaseSync } from 'node:sqlite';
import fs from 'node:fs';
import worker from '../dist/server/index.js';
import { cents,validateContent } from '../server/domain.js';
const origin='https://parish.example';
function database(){const sqlite=new DatabaseSync(':memory:');for(const file of fs.readdirSync('drizzle').filter(x=>x.endsWith('.sql')).sort())sqlite.exec(fs.readFileSync('drizzle/'+file,'utf8'));
 const wrap=(sql,args=[])=>({bind(...a){return wrap(sql,a);},async first(){return sqlite.prepare(sql).get(...args)||null;},async all(){return {results:sqlite.prepare(sql).all(...args)};},async run(){const out=sqlite.prepare(sql).run(...args);return {meta:{changes:Number(out.changes)}};},sql,args});
 return {sqlite,prepare:wrap,async batch(statements){sqlite.exec('BEGIN');try{const results=statements.map(s=>{const stmt=sqlite.prepare(s.sql);if(/^\s*SELECT/i.test(s.sql))return {results:stmt.all(...s.args)};const r=stmt.run(...s.args);return {results:[],meta:{changes:Number(r.changes)}};});sqlite.exec('COMMIT');return results;}catch(error){sqlite.exec('ROLLBACK');throw error;}}};}
function environment(){const bucket=new Map();return {ADMIN_EMAIL:'admin@example.com',DB:database(),BUCKET:{async put(key,value){bucket.set(key,new Uint8Array(value));},async get(key){return bucket.has(key)?{body:bucket.get(key)}:null;},async delete(key){bucket.delete(key);}}};}
async function call(env,path,{method='GET',body,admin=false,userId='owner-site-id',email='admin@example.com',foreign=false,raw=false}={}){const headers={};if(admin){headers['oai-authenticated-user-id']=userId;headers['oai-authenticated-user-email']=email;}if(method!=='GET'){headers.origin=foreign?'https://attacker.example':origin;headers['x-parish-request']='1';if(!raw)headers['content-type']='application/json';}const response=await worker.fetch(new Request(origin+path,{method,headers,body:body===undefined?undefined:raw?body:JSON.stringify(body)}),env);const contentType=response.headers.get('content-type')||'';const value=contentType.includes('json')?await response.json():contentType.includes('image/')?await response.arrayBuffer():await response.text();return {status:response.status,value,headers:response.headers};}
const post={kind:'post',title:'Parish story',body:'A community story.',images:[],status:'draft',data:{excerpt:'An introduction',author:'Parish Office'}};
const collection={kind:'collection',title:'Sunday collection',body:'',images:[],status:'draft',data:{date:'2026-09-13',lines:[{label:'First collection',amount:'1200.10'},{label:'Second collection',amount:'200.20'}],note:'Thank you.'}};
test('Parish directory preserves current and former terms and keeps draft profiles private',async()=>{const env=environment();const profile={kind:'person',title:'Test profile',body:'A test biography.',images:[],status:'draft',data:{group:'priest',role:'Parish priest',terms:[{role:'Parish priest',startYear:2023,endYear:null,current:true,notes:'Current term'},{role:'Parochial vicar',startYear:2018,endYear:2021,current:false,notes:'Previous ministry'}]}};const created=await call(env,'/api/admin/content',{method:'POST',body:profile,admin:true});assert.equal(created.status,201);assert.equal((await call(env,'/api/public/records?kind=person')).value.count,0);assert.equal((await call(env,'/api/admin/content/'+created.value.id,{method:'PUT',body:{...profile,status:'published',version:1},admin:true})).status,200);const current=(await call(env,'/api/public/records?kind=person&group=priest&tenure=current')).value;assert.equal(current.count,1);assert.equal(current.items[0].data.terms.length,2);assert.equal((await call(env,'/api/public/records?kind=person&tenure=former')).value.count,0);const former={...profile,title:'Former staff',status:'published',data:{group:'staff',role:'Secretary',terms:[{role:'Secretary',startYear:null,endYear:null,current:false,notes:'Dates are not recorded'}]}};assert.equal((await call(env,'/api/admin/content',{method:'POST',body:former,admin:true})).status,201);assert.equal((await call(env,'/api/public/records?kind=person&group=staff&tenure=former')).value.count,1);assert.throws(()=>validateContent({...profile,data:{...profile.data,terms:[{role:'Priest',startYear:2025,endYear:2020,current:false}]}}),/before/);});
test('Slideshow photographs, editable page content, and section settings persist safely',async()=>{const env=environment(),bytes=fs.readFileSync('public/assets/rosary.jpg');const photos=[];for(let n=0;n<2;n++)photos.push((await call(env,'/api/admin/media?filename=rosary.jpg&alt=Background',{method:'POST',body:bytes,raw:true,admin:true})).value.id);const schema=(await call(env,'/api/admin/copy-schema',{admin:true})).value.fields;assert.ok(schema.length>70);const key=schema.find(f=>f.group==='About the parish').key;const data={heroImage:photos[0],heroImages:photos,aboutImage:'',address:'Bongao',heroInterval:5,heroOverlay:65,heroPosition:'top',heroAlignment:'center',heroAutoplay:false,copy:{[key]:'Updated parish content',peopleTitle:'Our parish servants'},sectionVisibility:{quote:false},version:0};const saved=await call(env,'/api/admin/settings',{method:'PUT',body:data,admin:true});assert.equal(saved.status,200);const out=(await call(env,'/api/public/settings')).value;assert.deepEqual(out.heroImages,photos);assert.equal(out.copy[key],'Updated parish content');assert.equal(out.sectionVisibility.quote,false);assert.equal(out.heroAutoplay,false);assert.equal((await call(env,'/media/'+photos[1])).status,200);assert.equal((await call(env,'/api/admin/media/'+photos[1],{method:'DELETE',body:{},admin:true})).status,409);assert.equal((await call(env,'/api/admin/settings',{method:'PUT',body:{...data,version:1,mapUrl:'javascript:alert(1)'},admin:true})).status,400);});
test('Money validation and schedule dates reject invalid or ambiguous inputs',()=>{assert.equal(cents('0.10')+cents('0.20'),30);for(const value of ['-1','NaN','1e3','0.001'])assert.throws(()=>cents(value));assert.throws(()=>validateContent({...collection,data:{...collection.data,date:'2026-09-14'}}),/Sunday/);assert.throws(()=>validateContent({...post,kind:'event',data:{start:'2026-02-30T12:00:00+08:00',end:'2026-03-03T12:00:00+08:00',location:'Parish'}}),/valid date/);assert.throws(()=>validateContent({...post,kind:'schedule',data:{category:'Mass',recurrence:'weekly',days:[],startTime:'08:00'}}),/at least one day/);});
test('Public pages work, APIs require the owner, and cross-origin writes are denied',async()=>{const env=environment();assert.equal((await call(env,'/')).status,200);assert.equal((await call(env,'/collections')).status,200);assert.match((await call(env,'/admin')).value,/Sign in with ChatGPT/);assert.equal((await call(env,'/api/admin/content',{method:'POST',body:post})).status,401);assert.equal((await call(env,'/api/admin/content',{method:'POST',body:post,admin:true,email:'other@example.com'})).status,403);assert.equal((await call(env,'/api/admin/content',{method:'POST',body:post,admin:true,foreign:true})).status,403);assert.equal((await call(env,'/admin',{admin:true})).status,200);assert.equal((await call(env,'/api/admin/session',{admin:true,userId:'different-id'})).status,403);assert.equal((await call(env,'/admin.html',{admin:true,email:'other@example.com'})).status,403);});
test('Drafts, publishing, escaping, unpublishing, and stale edits form a complete workflow',async()=>{const env=environment();const created=await call(env,'/api/admin/content',{method:'POST',body:{...post,title:'A <script>alert(1)</script> story',body:'<img src=x onerror=alert(1)>\n\nA safe paragraph.'},admin:true});assert.equal(created.status,201);const row=created.value;assert.equal((await call(env,'/api/public/records?kind=post')).value.count,0);assert.equal((await call(env,'/blog/'+row.id)).status,404);const edit={...post,title:row.title,body:row.body,status:'published',version:row.version};const published=await call(env,'/api/admin/content/'+row.id,{method:'PUT',body:edit,admin:true});assert.equal(published.status,200);assert.equal((await call(env,'/api/public/records?kind=post')).value.count,1);const html=(await call(env,'/blog/'+row.id)).value;assert.ok(html.includes('&lt;script&gt;'));assert.ok(!html.includes('<script>alert'));assert.ok(html.includes('&lt;img'));const stale=await call(env,'/api/admin/content/'+row.id,{method:'PUT',body:edit,admin:true});assert.equal(stale.status,409);const draft=await call(env,'/api/admin/content/'+row.id,{method:'PUT',body:{...edit,status:'draft',version:published.value.version},admin:true});assert.equal(draft.status,200);assert.equal((await call(env,'/blog/'+row.id)).status,404);assert.equal((await call(env,'/api/admin/audit',{admin:true})).value.items.length,3);});
test('Sunday reports calculate exact totals, exclude drafts, prevent duplicates and preserve corrections',async()=>{const env=environment();const created=await call(env,'/api/admin/content',{method:'POST',body:{...collection,amountCents:1},admin:true});assert.equal(created.status,201);assert.equal(created.value.amount_cents,140030);assert.equal((await call(env,'/api/public/records?kind=collection&year=2026')).value.totalCents,0);const duplicate=await call(env,'/api/admin/content',{method:'POST',body:collection,admin:true});assert.equal(duplicate.status,409);const published=await call(env,'/api/admin/content/'+created.value.id,{method:'PUT',body:{...collection,status:'published',version:1},admin:true});assert.equal(published.status,200);let report=(await call(env,'/api/public/records?kind=collection&year=2026')).value;assert.equal(report.count,1);assert.equal(report.totalCents,140030);const fixed=await call(env,'/api/admin/content/'+created.value.id,{method:'PUT',body:{...collection,status:'published',data:{...collection.data,lines:[{label:'Corrected total',amount:'1500.30'}]},version:2},admin:true});assert.equal(fixed.status,200);assert.equal((await call(env,'/api/public/records?kind=collection&year=2026')).value.totalCents,150030);const audit=(await call(env,'/api/admin/audit',{admin:true})).value.items;assert.ok(audit.some(a=>JSON.parse(a.before_json||'null')?.amount_cents===140030&&JSON.parse(a.after_json||'null')?.amountCents===150030));assert.equal((await call(env,'/api/admin/content/'+created.value.id,{method:'DELETE',body:{version:3},admin:true})).status,200);assert.equal((await call(env,'/api/public/records?kind=collection&year=2026')).value.count,0);assert.equal((await call(env,'/api/admin/audit',{admin:true})).value.items.length,4);});
test('Photo upload is durable and private until published; in-use photos cannot be deleted',async()=>{const env=environment(),bytes=fs.readFileSync('public/assets/rosary.jpg');assert.equal((await call(env,'/api/admin/media?filename=test.svg&alt=Test',{method:'POST',body:new TextEncoder().encode('<svg><script>alert(1)</script></svg>'),raw:true,admin:true})).status,415);const uploaded=await call(env,'/api/admin/media?filename=rosary.jpg&alt=Rosary%20beads',{method:'POST',body:bytes,raw:true,admin:true});assert.equal(uploaded.status,201);const media=uploaded.value.id;assert.equal((await call(env,'/media/'+media)).status,404);assert.equal((await call(env,'/media/'+media,{admin:true})).status,200);const created=await call(env,'/api/admin/content',{method:'POST',body:{...post,images:[media]},admin:true});assert.equal((await call(env,'/media/'+media)).status,404);assert.equal((await call(env,'/api/admin/media/'+media,{method:'DELETE',body:{},admin:true})).status,409);assert.equal((await call(env,'/api/admin/content/'+created.value.id,{method:'PUT',body:{...post,images:[media],status:'published',version:1},admin:true})).status,200);assert.equal((await call(env,'/media/'+media)).status,200);const unpublish=await call(env,'/api/admin/content/'+created.value.id,{method:'PUT',body:{...post,images:[media],status:'draft',version:2},admin:true});assert.equal(unpublish.status,200);assert.equal((await call(env,'/media/'+media)).status,404);assert.equal((await call(env,'/api/admin/content/'+created.value.id,{method:'DELETE',body:{version:3},admin:true})).status,200);assert.equal((await call(env,'/api/admin/media/'+media,{method:'DELETE',body:{},admin:true})).status,200);assert.equal((await call(env,'/media/'+media,{admin:true})).status,404);});
test('Homepage settings publish selected photos and detect stale updates',async()=>{const env=environment();const photo=(await call(env,'/api/admin/media?filename=rosary.jpg&alt=Rosary',{method:'POST',body:fs.readFileSync('public/assets/rosary.jpg'),raw:true,admin:true})).value;const settings={heroImage:photo.id,aboutImage:'',welcome:'Welcome everyone',phone:'+63 900 000 0000',email:'parish@example.com',address:'Bongao, Tawi-Tawi',officeHours:'Tuesday to Saturday',version:0};assert.equal((await call(env,'/api/admin/settings',{method:'PUT',body:settings,admin:true})).status,200);assert.equal((await call(env,'/api/public')).value.settings.welcome,'Welcome everyone');assert.equal((await call(env,'/media/'+photo.id)).status,200);assert.equal((await call(env,'/api/admin/settings',{method:'PUT',body:settings,admin:true})).status,409);assert.equal((await call(env,'/api/admin/media/'+photo.id,{method:'DELETE',body:{},admin:true})).status,409);});
test('Events use Philippine timestamps; regular and one-time schedules are published',async()=>{const env=environment();const event={...post,kind:'event',status:'published',title:'Parish gathering',data:{start:'2026-10-01T10:00:00+08:00',end:'2026-10-01T12:00:00+08:00',location:'Parish hall'}};const created=await call(env,'/api/admin/content',{method:'POST',body:event,admin:true});assert.equal(created.status,201);assert.equal(created.value.data.start,'2026-10-01T02:00:00.000Z');const weekly={...post,kind:'schedule',status:'published',title:'Sunday Mass',data:{category:'Mass',recurrence:'weekly',days:[0],startTime:'08:00',endTime:'09:00',location:'Church'}};const once={...weekly,title:'Confession',data:{category:'Confession',recurrence:'once',date:'2026-10-03',startTime:'16:00'}};assert.equal((await call(env,'/api/admin/content',{method:'POST',body:weekly,admin:true})).status,201);assert.equal((await call(env,'/api/admin/content',{method:'POST',body:once,admin:true})).status,201);assert.equal((await call(env,'/api/public/records?kind=schedule')).value.count,2);});

test('Homepage first response uses saved photos and slideshow order without a default-image flash',async()=>{
 const env=environment(),first='m_11111111-1111-4111-8111-111111111111',second='m_22222222-2222-4222-8222-222222222222',about='m_33333333-3333-4333-8333-333333333333';
 try{
  const save=data=>env.DB.sqlite.prepare("INSERT INTO settings (id,data,version,updated_at,mutation) VALUES ('parish',?,1,'2026-09-15','test') ON CONFLICT(id) DO UPDATE SET data=excluded.data,version=version+1").run(JSON.stringify(data));
  save({heroImage:second,heroImages:[first,second],aboutImage:about,heroPosition:'top'});
  const page=await call(env,'/');assert.equal(page.status,200);assert.equal(page.headers.get('cache-control'),'no-store');
  assert.match(page.value,new RegExp('data-home-photo="hero" style="background-image:url\\(\'/media/'+first+'\'\\);background-position:top"'));
  assert.match(page.value,new RegExp('data-home-photo="about" src="/media/'+about+'"'));
  assert.match(page.value,new RegExp('rel="preload" as="image" href="/media/'+first+'"'));
  assert.ok(!page.value.includes('rosary.jpg'));assert.ok(!page.value.includes('id="image-credit"'));
  save({heroImages:[second,first],aboutImage:about});const refreshed=await call(env,'/');assert.match(refreshed.value,new RegExp('background-image:url\\(\'/media/'+second+'\'\\)'));
  save({heroImage:first,heroImages:[],aboutImage:about});assert.ok((await call(env,'/')).value.includes("background-image:url('/media/"+first+"')"));
  save({heroImages:[],heroImage:'',aboutImage:''});const defaults=await call(env,'/');assert.ok(defaults.value.includes("background-image:url('/assets/rosary.jpg')"));assert.ok(defaults.value.includes('src="/assets/rosary.jpg"'));assert.ok(defaults.value.includes('id="image-credit"'));
  const unavailable=await call({...env,DB:undefined},'/');assert.equal(unavailable.status,200);assert.ok(!unavailable.value.includes('rosary.jpg'));assert.ok(unavailable.value.includes('data-home-photo="about" hidden'));
 }finally{env.DB.sqlite.close();}
});
